# Generated by Django 4.1.5 on 2024-04-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
