# Generated by Django 4.1.5 on 2024-04-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_report_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
