# Generated by Django 4.1.5 on 2024-04-02 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_report_latitude_remove_report_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('street_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('time_slot', models.IntegerField(validators=[django.core.validators.MinValueValidator(9), django.core.validators.MaxValueValidator(18)])),
                ('date_of_pickup', models.DateField()),
                ('status', models.CharField(choices=[('pickedup', 'Picked Up'), ('pending', 'Pending')], default='pending', max_length=8)),
                ('type', models.CharField(choices=[('dry', 'Dry'), ('wet', 'Wet'), ('toxic', 'Toxic')], default='dry', max_length=5)),
            ],
        ),
    ]
